baseURL = 'http://konveyor.github.io/'
languageCode = 'en-us'
title = 'Documentation for Konveyor projects'
theme = ["github.com/google/docsy"]
[outputs]
home = [ "HTML", "RSS", "JSON"]
[[menu.main]]
  name = "Components"
  weight = 1
  identifier = "components"
[[menu.main]]
  url = "/components/konveyor-hub"
  name = "Konveyor Hub"
  parent = "components"
  weight = 1
[[menu.main]]
  url = "/components/konveyor-cli"
  name = "Konveyor CLI"
  parent = "components"
  weight = 2
[[menu.main]]
  url = "/components/kai"
  name = "Konveyor AI"
  parent = "components"
  weight = 3
[[menu.main]]
  name = "Documentation"
  weight = 2
  url = "/docs"
[[menu.main]]
  name = "Community"
  weight = 3
  url = "/community"
[[menu.main]]
  name = "Ecosystem"
  weight = 4
  url = "/ecosystem"
[[menu.main]]
  name = "Blog"
  weight = 5
  url = "/blog"
[params]
  # Google Tag Manager
  gtm_id = "GTM-TKPDMS3"
  # offline search
  offlineSearch = true
[params.ui]
sidebar_search_disable = false
[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name = "User mailing list"
	url = "https://example.org/mail"
	icon = "fa fa-envelope"
        desc = "Discussion and help from your fellow users"
[[params.links.user]]
	name ="Twitter"
	url = "https://example.org/twitter"
	icon = "fab fa-x-twitter"
        desc = "Follow us on Twitter to get the latest news!"
[[params.links.user]]
	name = "Stack Overflow"
	url = "https://example.org/stack"
	icon = "fab fa-stack-overflow"
        desc = "Practical questions and curated answers"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/google/docsy"
	icon = "fab fa-github"
        desc = "Development takes place here!"
[[params.links.developer]]
	name = "Slack"
	url = "https://example.org/slack"
	icon = "fab fa-slack"
        desc = "Chat with other project developers"
[[params.links.developer]]
	name = "Developer mailing list"
	url = "https://example.org/mail"
	icon = "fa fa-envelope"
        desc = "Discuss development issues around the project"

# Key konveyor components section on the main page
[[params.components]]
src = "/images/konveyor-ui-dashboard.png"
title = "Konveyor Hub"
cta_primary_title = "Get Started"
cta_primary_url = "/docs"
cta_secondary_title = "Learn More"
cta_secondary_url = "/components/konveyor-hub"
description = "Automate the replatforming of your applications to Kubernetes with Move2Kube. With this tool, you can translate your source files to Kubernetes artifacts to quickly get your workloads running on Kubernetes."

[[params.components]]
src = "/images/konveyor-ui-dashboard.png"
title = "Konveyor CLI"
cta_primary_title = "Get Started"
cta_primary_url = "/docs"
cta_secondary_title = "Learn More"
cta_secondary_url = "/components/konveyor-cli"
description = "Automate the replatforming of your applications to Kubernetes with Move2Kube. With this tool, you can translate your source files to Kubernetes artifacts to quickly get your workloads running on Kubernetes."

[[params.components]]
src = "/images/konveyor-ui-dashboard.png"
title = "Konveyor AI"
cta_primary_title = "Get Started"
cta_primary_url = "/docs"
cta_secondary_title = "Learn More"
cta_secondary_url = "/components/kai"
description = "Automate the replatforming of your applications to Kubernetes with Move2Kube. With this tool, you can translate your source files to Kubernetes artifacts to quickly get your workloads running on Kubernetes."

# community supporters
[[params.supporters]]
logo = "/images/community-supporters/claranet.svg"
company = "claranet"

[[params.supporters]]
logo = "/images/community-supporters/ibm-research.svg"
company = "ibm research"

[[params.supporters]]
logo = "/images/community-supporters/redhat.svg"
company = "redhat"
