# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

[build.environment]
GO_VERSION = "1.22"
HUGO_VERSION = "0.145.0"